Chat2-Test/app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()

def create_app(debug=False):
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'chat2_test_0920'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='/test')

    socketio.init_app(app)
    return app

Chat2-Test/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

Chat2-Test/app/main/routes.py
# coding: utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')


from flask import render_template, request, session, redirect, url_for, flash
from . import main
from app.db import User, call_query
from app.manager import input_data, Password


@main.route('/', methods=['GET', 'POST'])
def index():
    if request.args.get('clear'):
        session.clear()

    if request.method == 'POST':
        error = False

        session['userid'] = request.form['userid']
        session['password'] = request.form['password']
        session['username'] = request.form['username']

        if request.form['userid'] == '':
            flash('필수 입력란입니다.', 'id')
            error = True
        if request.form['password'] == '':
            flash('필수 입력란입니다.', 'pw')
            error = True
        if request.form['username'] == '':
            flash('필수 입력란입니다.', 'name')
            error = True
        
        if error:
            return redirect(url_for('main.signUp'))
        
        input_data(userid=request.form['userid'], 
                    password=request.form['password'], 
                    username=request.form['username'])
        
    return render_template('index.html', page='대기실')


@main.route('/signUp', methods=['GET'])
def signUp():
    return render_template('signUp.html', page='계정 만들기')


@main.route('/chat', methods=['POST'])
@call_query
def chat(query):
    error = False

    userid = session['userid'] = request.form['userid']
    password = session['password'] = request.form['password']
    roomname = session['roomname'] = request.form['roomname']

    if not userid:
        error = True
        flash('아이디를 입력하세요.', 'id')
    elif query.filter(User.userid == userid).count() == 0:
        error = True
        flash('유효한 아이디를 입력하세요.', 'id')
        session.pop('userid')

    if not password:
        error = True
        flash('비밀번호를 입력하세요.', 'pw')
    else:
        user = query.filter_by(userid=userid).first()

        if not user or not user.password_hash == Password(password):
            error = True
            flash('잘못된 비밀번호입니다.', 'pw')
            session.pop('password')
        
    if not roomname:
        error = True
        flash('방제목을 입력하세요.', 'room')

    if error:
        return redirect(url_for('main.index'))
    
    session['username'] = query.filter_by(userid=userid).one().username
    return render_template('chat.html', page=roomname)

Chat2-Test/app/templates/chat.html
{% extends 'layout.html' %}
{% block head %}
	<script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
	<script type="text/javascript">
		var socket
		$(document).ready(function() {
			namespace = '/chat';

			socket = io.connect('http://' + document.domain + ':' + location.port + namespace);

			// 소켓 연결 시 자동적으로 실행되는 connect 함수를 통하여 방에 입장
			socket.on('connect', function() {
				socket.emit('room_joined', {});
			});

			socket.on('notice', function(msg) {
				$('#log').val($('#log').val() + msg.notice + '\n');
				$('#log').scrollTop($('#log')[0].scrollHeight);
			});

			socket.on('chat', function(msg) {
				$('#log').val($('#log').val() + msg.chat + '\n');
				$('#log').scrollTop($('#log')[0].scrollHeight);
			});

			$('form#chat').submit(function(event) {
				if ($('#text').val() == '')
					return false;
				socket.emit('chat_submit', {msg: $('#text').val()});
				$('#text').val('');
				return false;
			});
		});

		function leave_room() {
			socket.emit('room_left', {}, function() {
				socket.disconnect();

				window.location.href = "{{ url_for('main.index', clear=True) }}";
			});
		}
		</script>
{% endblock %}
{% block body %}
	<div class=page style='width: 36.5em; height: 25em'>
		<h1>{{ page }}</h1>
		<textarea id='log' class='chat_input' style='width: 43.5em; height: 20em; margin-bottom: 0.5em;' readonly></textarea><br>
		<form id='chat' method='POST' action='#'>
			<input type='text' id='text' class='chat_input' style='width: 38em; height:1.5em; text-indent: 0.5em;'>
			<input type='submit' class='chat_input' style='width: 5em;' value='전송'>
		</form>
		<br>
		<a href='#' onclick='leave_room();' style='margin-top: 0.5em; color: #FE2E2E; font-weight: bold; font-size: 10pt; float: right;'>방 나가기</a>
	</div>
{% endblock %}

Chat2-Test/app/templates/index.html
{% extends 'layout.html' %}
{% block head %}
	<!-- Empty -->
{% endblock %}
{% block body %}
	<div class=page style='width: 20em;'>
		<center>
			<h1>{{ page }}</h1>
			<form method='POST' action="{{ url_for('main.chat') }}">
				<br><br>
				<input type='text' name='userid' class='index_input' placeholder='아이디' value={{ session['userid'] }}>
				{% for message in get_flashed_messages(category_filter=["id"]) %}
				<br><div class=index_flash>{{ message }}</div>
				{% endfor %}
				<br>
				<input type='password' name='password' class='index_input' placeholder='비밀번호' value={{ session['password'] }}>
				{% for message in get_flashed_messages(category_filter=["pw"]) %}
				<br><div class=index_flash>{{ message }}</div>
				{% endfor %}
				<br><br>
				<input type='text' name='roomname' class='index_input' placeholder='방제목'  value={{ session['roomname'] }}>
				{% for message in get_flashed_messages(category_filter=["room"]) %}
				<br><div class=index_flash>{{ message }}</div>
				{% endfor %}
				<br>
				<input type='submit' class='index_input' value='입장'>
				<br><br>
			</form>
			<a href="{{ url_for('main.signUp') }}" style='color: #0080FF; font-size: 10pt;'>계정 만들기</a>
		</center>
	</div>
{% endblock %}

Chat2-Test/app/templates/layout.html
<!doctype html>
<meta charset=utf-8>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}"
<html lang='ko'>
	<head>
		<title>도란도란 대화방 - {{ page }}</title>
		{% block head %}
		{% endblock %}
	</head>
	<body>
		{% block body %}
		{% endblock %}
	</body>
</html>

Chat2-Test/app/templates/signUp.html
{% extends 'layout.html' %}
{% block head %}
	<!-- Empty -->
{% endblock %}
{% block body %}
	<div class=page style='width: 18em;'>
		<center>
			<h1>{{ page }}</h1>
			<form method='POST' action="{{ url_for('main.index') }}" style='vertical-align: left;'>
				<br><br>
				<input type='text' name='userid' class='signUp_input' placeholder='아이디' value={{ session['userid'] }}>
				{% for message in get_flashed_messages(category_filter=["id"]) %}
				<div class=signUp_flash>{{ message }}</div>
				{% endfor %}
				<br>
				<input type='password' name='password' class='signUp_input' placeholder='비밀번호' value={{ session['password'] }}>
				{% for message in get_flashed_messages(category_filter=["pw"]) %}
				<div class=signUp_flash>{{ message }}</div>
				{% endfor %}
				<br>
				<input type='text' name='username' class='signUp_input' placeholder='사용자 이름' value={{ session['username'] }}>
				{% for message in get_flashed_messages(category_filter=["name"]) %}
				<div class=signUp_flash>{{ message }}</div>
				{% endfor %}
				<br>
				<input type='submit' class='signUp_input' value='가입하기'>
			</form>
			<a href="{{ url_for('main.index', clear=True) }}" style='color: #0080FF; font-size: 10pt;'>돌아가기</a>
		</center>
	</div>
{% endblock %}

Chat2-Test/app/templates/test.html
<!doctype html>
<meta charset="utf-8">
<html>
	<head>
		<title>테스트용</title>
		<script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				namespace = '/test';

				var socket = io.connect('http://' + document.domain + ':' + location.port + namespace);
				
				socket.on('response', function(msg) {
					$('#log').append('<p>' + msg.username + ': ' + msg.data + '</p>');
				});

				$('form#broadcast').submit(function(event) {
					if ($('#broadcast_data').val() == "")
						return false;
					socket.emit('broadcast_event', {data: $('#broadcast_data').val()});
					$('#broadcast_data').val("");
					return false;
				});

				$('form#disconnect').submit(function(event) {
					socket.emit('disconnect_request');
					return false;
				});
			});
		</script>
	</head>
	<body>
		<h1>테스트..!</h1>
		<div id="log">
			<!-- broadcast_data -->
		</div>
		<form id="broadcast" method="POST" action='#'>
			<input type="text" name="broadcast_data" id="broadcast_data">
			<input type="submit" value="Submit">
		</form>
		<form id="disconnect" method="POST" action='#'>
			<input type="submit" value="Disconnect">
		</form>
	</body>
</html>